### ISSUE TITLE
在scratch3没法加载

### ISSUE THREAD

**Issue by hhnightdream** [IBM/taxinomitis-docs#10]
在scratch3上没法加载该文件，请问为什么，谢谢！

**Comment by dalelane** [comment]
什么文件？

**Comment by hhnightdream** [comment]
shypanda.sb3文件，谢了

**Comment by dalelane** [comment]
您使用的是https://machinelearningforkids.co.uk/scratch3吗？

您需要使用由儿童机器学习站点提供的Scratch版本。可以通过单击项目页面中的Scratch（或'Scratch 3'）按钮来启动它。

**Comment by hhnightdream** [comment]
已经可以了，3ks

**Comment by dalelane** [comment]
你使用什么网络浏览器？

**Comment by hhnightdream** [comment]
已经按照您的要求进行操作，所以解决了，多谢！


| |
hhnightdream
|
|
hhnightdream@163.com
|
签名由网易邮箱大师定制


在2019年04月18日 09:09，Dale Lane<notifications@github.com> 写道：

你使用什么网络浏览器？
